// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CommandReducer from "../command_reducer";
import JoinReducer from "../join_reducer";

export type CommandParams = __Infer<typeof CommandReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;

