// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Member = __t.object("Member", {
  connection: __t.connectionId(),
  identity: __t.identity(),
  room: __t.string(),
  name: __t.string(),
});
export type Member = __Infer<typeof Member>;

export const Room = __t.object("Room", {
  code: __t.string(),
  state: __t.string(),
  snapshot: __t.string(),
  revision: __t.u32(),
  players: __t.u32(),
  updated: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const Timer = __t.object("Timer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type Timer = __Infer<typeof Timer>;

