import { enemies,towers,levels,waves } from '../shared/catalog';
function lua(v:unknown):string { if(Array.isArray(v))return '{'+v.map(lua).join(',')+'}';if(v!==null&&typeof v==='object')return '{'+Object.entries(v).map(([k,v])=>`${k}=${lua(v)}`).join(',')+'}';return JSON.stringify(v); }
await Bun.write(new URL('../../td/catalog.luau',import.meta.url),`-- Generated by bun run catalog. Edit shared/catalog.ts.\nreturn ${lua({enemies,towers,levels:levels.map(l=>({...l,pads:l.pads.map(([x,y])=>({x,y}))})),waves})}\n`);
